theme: readthedocs
site_name: Mau Mau

pages:
  - Home: index.md
  - User Guide:
    - Installation: guide/installation.md
    - Command line usage: guide/usage.md
    - Rules of the game: guide/rules.md
  - Implemenation:
    - OOOMMM: implementation/ooommm.md
    - Implementation: implementation/remarks.md
    - Explore the code: implementation/explore.md
  - Developer Guide:
    - Getting started: dev/getting-started.md
    - Static code analysis: dev/static-analysis.md
    - Automatic tests: dev/tests.md
    - Tox (developer frontend): dev/tox.md
    - Continuous intergration: dev/travis-ci.md
    - Working on documentation: dev/docs.md

site_dir: docs/_build

repo_url: https://github.com/obestwalter/mau-mau

strict: False

markdown_extensions:
    - toc:
        permalink: Â¶
