pages:
  - Home: index.md
  - User Guide:
    - Installation: guide/installation.md
    - Command line access: guide/usage.md
    - Rules of Mau Mau: guide/rules.md
  - Implemenation:
    - OOOMMM: implementation/ooommm.md
    - Remarks: implementation/remarks.md
    - Explore the code: implementation/explore.md
  - Developer Guide:
    - Getting started: dev/getting-started.md
    - Static code analysis: dev/static-analysis.md
    - Automatic tests: dev/tests.md
    - Using Tox: dev/tox.md
    - Continuous intergration: dev/ci.md
    - Working on documentation: dev/docs.md

#include_404: True
markdown_extensions:
    - toc:
        permalink: True #Â¶
repo_url: https://github.com/obestwalter/mau-mau
site_name: Mau Mau
#strict: True
theme: united
